import{a as v,S as P,i as q}from"./assets/vendor-64b55ca9.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function c(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=c(e);fetch(e.href,r)}})();async function m(o){const t="https://pixabay.com",c="/api/",n="?key=42408826-646f1c33dda85bc33c99aac2a",e=`&q=${o}&image_type=photo&orientation=horizontal&safesearch=true`,r=t+c+n+e;try{return(await v.get(r)).data}catch(s){throw new Error(s.response.status)}}const u=document.querySelector(".gallery");function f(o){const t=o.hits.map(({webformatURL:n,largeImageURL:e,tags:r,likes:s,views:E,comments:w,downloads:S})=>`<li class="gallery-item">
  <a class="gallery-link" href="${e}">
    <img class="gallery-img" src="${n}" alt="${r}" />
  <div class="image-description">
    <p><b>Likes: </b>${s}</p>
    <p><b>Views: </b>${E}</p>
    <p><b>Comments: </b>${w}</p>
    <p><b>Downloads: </b>${S}</p>
  </div>
  </a>
</li>`).join("");u.insertAdjacentHTML("beforeend",t),new P(".gallery a",{captions:!0,captionDelay:250,captionsData:"alt",captionPosition:"bottom"}).refresh()}const $=document.querySelector(".img-search-form"),p=document.querySelector(".loader"),h=document.querySelector(".load-more-btn");let l,i,y;$.addEventListener("submit",M);h.addEventListener("click",O);async function M(o){if(o.preventDefault(),g(),u.innerHTML="",l=o.target.elements.query.value.trim(),i=1,l===""){a("Sorry, there are no search terms entered. Please try again!");return}b();try{const t=await m(l,i);if(y=Math.ceil(t.totalHits/15),t.totalHits===0){d(),a("Sorry, there are no images matching your search query. Please try again!");return}f(t)}catch(t){a(t)}d(),L(),o.target.reset()}async function O(){i+=1,b();try{const t=await m(l,i);f(t)}catch(t){a(t)}d(),L();const o=u.firstElementChild.getBoundingClientRect().height;scrollBy({behavior:"smooth",top:o*2})}function x(){h.classList.remove("hidden")}function g(){h.classList.add("hidden")}function b(){p.classList.remove("hidden")}function d(){p.classList.add("hidden")}function a(o){q.error({message:o,messageColor:"white",backgroundColor:"red",position:"topRight"})}function L(){i>=y?(g(),a("We're sorry, but you've reached the end of search results.")):x()}
//# sourceMappingURL=commonHelpers.js.map
